/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoopsRouteImport } from './routes/loops'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as HooksRouteImport } from './routes/hooks'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as AgentTeamsRouteImport } from './routes/agent/teams'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'
import { Route as AgentReferenceUrlRouteImport } from './routes/agent/reference-url'
import { Route as AgentPluginsRouteImport } from './routes/agent/plugins'
import { Route as AgentCapabilitiesRouteImport } from './routes/agent/capabilities'
import { Route as AgentAiUrlRouteImport } from './routes/agent/ai-url'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopsRoute = LoopsRouteImport.update({
  id: '/loops',
  path: '/loops',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRoute = HooksRouteImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const AgentTeamsRoute = AgentTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)
const AgentReferenceUrlRoute = AgentReferenceUrlRouteImport.update({
  id: '/reference-url',
  path: '/reference-url',
  getParentRoute: () => AgentRoute,
} as any)
const AgentPluginsRoute = AgentPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AgentRoute,
} as any)
const AgentCapabilitiesRoute = AgentCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAiUrlRoute = AgentAiUrlRouteImport.update({
  id: '/ai-url',
  path: '/ai-url',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/history': typeof HistoryRoute
  '/hooks': typeof HooksRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/loops': typeof LoopsRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/workflows': typeof WorkflowsRoute
  '/agent/ai-url': typeof AgentAiUrlRoute
  '/agent/capabilities': typeof AgentCapabilitiesRoute
  '/agent/plugins': typeof AgentPluginsRoute
  '/agent/reference-url': typeof AgentReferenceUrlRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/teams': typeof AgentTeamsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/history': typeof HistoryRoute
  '/hooks': typeof HooksRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/loops': typeof LoopsRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/workflows': typeof WorkflowsRoute
  '/agent/ai-url': typeof AgentAiUrlRoute
  '/agent/capabilities': typeof AgentCapabilitiesRoute
  '/agent/plugins': typeof AgentPluginsRoute
  '/agent/reference-url': typeof AgentReferenceUrlRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/teams': typeof AgentTeamsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/history': typeof HistoryRoute
  '/hooks': typeof HooksRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/loops': typeof LoopsRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/workflows': typeof WorkflowsRoute
  '/agent/ai-url': typeof AgentAiUrlRoute
  '/agent/capabilities': typeof AgentCapabilitiesRoute
  '/agent/plugins': typeof AgentPluginsRoute
  '/agent/reference-url': typeof AgentReferenceUrlRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/teams': typeof AgentTeamsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/history'
    | '/hooks'
    | '/knowledge'
    | '/logs'
    | '/loops'
    | '/mcp'
    | '/models'
    | '/plugins'
    | '/schedule'
    | '/settings'
    | '/teams'
    | '/workflows'
    | '/agent/ai-url'
    | '/agent/capabilities'
    | '/agent/plugins'
    | '/agent/reference-url'
    | '/agent/skills'
    | '/agent/teams'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/history'
    | '/hooks'
    | '/knowledge'
    | '/logs'
    | '/loops'
    | '/mcp'
    | '/models'
    | '/plugins'
    | '/schedule'
    | '/settings'
    | '/teams'
    | '/workflows'
    | '/agent/ai-url'
    | '/agent/capabilities'
    | '/agent/plugins'
    | '/agent/reference-url'
    | '/agent/skills'
    | '/agent/teams'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/history'
    | '/hooks'
    | '/knowledge'
    | '/logs'
    | '/loops'
    | '/mcp'
    | '/models'
    | '/plugins'
    | '/schedule'
    | '/settings'
    | '/teams'
    | '/workflows'
    | '/agent/ai-url'
    | '/agent/capabilities'
    | '/agent/plugins'
    | '/agent/reference-url'
    | '/agent/skills'
    | '/agent/teams'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  ConfigRoute: typeof ConfigRouteWithChildren
  CredentialsRoute: typeof CredentialsRoute
  HistoryRoute: typeof HistoryRoute
  HooksRoute: typeof HooksRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LogsRoute: typeof LogsRoute
  LoopsRoute: typeof LoopsRoute
  McpRoute: typeof McpRoute
  ModelsRoute: typeof ModelsRoute
  PluginsRoute: typeof PluginsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  TeamsRoute: typeof TeamsRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loops': {
      id: '/loops'
      path: '/loops'
      fullPath: '/loops'
      preLoaderRoute: typeof LoopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks': {
      id: '/hooks'
      path: '/hooks'
      fullPath: '/hooks'
      preLoaderRoute: typeof HooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/teams': {
      id: '/agent/teams'
      path: '/teams'
      fullPath: '/agent/teams'
      preLoaderRoute: typeof AgentTeamsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/reference-url': {
      id: '/agent/reference-url'
      path: '/reference-url'
      fullPath: '/agent/reference-url'
      preLoaderRoute: typeof AgentReferenceUrlRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/plugins': {
      id: '/agent/plugins'
      path: '/plugins'
      fullPath: '/agent/plugins'
      preLoaderRoute: typeof AgentPluginsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/capabilities': {
      id: '/agent/capabilities'
      path: '/capabilities'
      fullPath: '/agent/capabilities'
      preLoaderRoute: typeof AgentCapabilitiesRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/ai-url': {
      id: '/agent/ai-url'
      path: '/ai-url'
      fullPath: '/agent/ai-url'
      preLoaderRoute: typeof AgentAiUrlRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface AgentRouteChildren {
  AgentAiUrlRoute: typeof AgentAiUrlRoute
  AgentCapabilitiesRoute: typeof AgentCapabilitiesRoute
  AgentPluginsRoute: typeof AgentPluginsRoute
  AgentReferenceUrlRoute: typeof AgentReferenceUrlRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentTeamsRoute: typeof AgentTeamsRoute
  AgentToolsRoute: typeof AgentToolsRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAiUrlRoute: AgentAiUrlRoute,
  AgentCapabilitiesRoute: AgentCapabilitiesRoute,
  AgentPluginsRoute: AgentPluginsRoute,
  AgentReferenceUrlRoute: AgentReferenceUrlRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentTeamsRoute: AgentTeamsRoute,
  AgentToolsRoute: AgentToolsRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  ConfigRoute: ConfigRouteWithChildren,
  CredentialsRoute: CredentialsRoute,
  HistoryRoute: HistoryRoute,
  HooksRoute: HooksRoute,
  KnowledgeRoute: KnowledgeRoute,
  LogsRoute: LogsRoute,
  LoopsRoute: LoopsRoute,
  McpRoute: McpRoute,
  ModelsRoute: ModelsRoute,
  PluginsRoute: PluginsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
